### ISSUE TITLE
Investigate how to utilize activitypub-behaviors (cross-referencing)

### ISSUE THREAD

**Issue by steve-bate** [steve-bate/activitypub-testsuite#6]
@gobengo@, I've been doing some investigation about how to cross-reference the activitypub-behaviors. I started adding metadata to the test cases, but it seems like an assertion-level metadata might be a better fit. Is the project still active (or maybe moved)? I get a 404 Not Found when I try to visit it on codeberg.

**Comment by gobengo** [comment]
@steve-bate Yeah, I moved it to a gitlab-powered provider, which has been more stable and featureful than codeberg. I don't plan to move it again. https://git.coop/socialweb.coop/activitypub-behaviors

I also published it to npm and have GitLab CI over there publishing new changes.
https://www.npmjs.com/package/@socialweb.coop/activitypub-behaviors

I set up an npm 'bin' script which allows for invoking the library via `npx` without needing to set up an npm project. It will print them all to stdout (here I pipe to `jq` to select only the first one and pretty print).
```
bengo@bengo ~/play/stevebate-activitypub-testing/apex-aptesting ⚡  npx @socialweb.coop/activitypub-behaviors | jq '.[:1][]' -s
{
  "type": "Behavior",
  "name": "intransient objects must have unique global identifiers",
  "content": "all objects distributed by the ActivityPub protocol MUST have unique global identifiers, unless they are intentionally transient\n",
  "origin": {
    "source": "https://www.w3.org/TR/activitypub/",
    "section": {
      "id": "https://www.w3.org/TR/activitypub/#obj-id",
      "branch": [
        3,
        1
      ]
    },
    "selector": {
      "type": "TextQuoteSelector",
      "exact": "all objects distributed by the ActivityPub protocol MUST have unique global identifiers, unless they are intentionally transient (short lived activities that are not intended to be able to be looked up, such as some kinds of chat messages or game notifications).\n",
      "prefix": "All Objects in [ActivityStreams] should have unique global identifiers. ActivityPub extends this requirement; \n",
      "suffix": "These identifiers must fall into one of the following groups:\n"
    }
  },
  "id": "urn:uuid:fc2bfa75-8fd0-45e0-809d-7aa3970be8ae",
  "uuid": "fc2bfa75-8fd0-45e0-809d-7aa3970be8ae"
}
```

**Comment by gobengo** [comment]
@steve-bate One way of cross referencing them may be via pytest marks (I'm not deeply familiar with pytest) to the urns (e.g. `urn:uuid:fc2bfa75-8fd0-45e0-809d-7aa3970be8ae`) andor URLs (e.g. `https://socialweb.coop/activitypub/behaviors/64d00f29-b0f5-4407-963f-5dce7c7dae2e/` but we could also eventually have a SWICG note with w3.org URLs).

Do you have any suggestions on a good way to cross reference, otherwise make use of them, or more data I should build into the data itself (e.g. eventually I want to explicitly have the rfc2119 requirementLevel in there but haven't prioritized it yet until I need it).

**Comment by steve-bate** [comment]
> @steve-bate One way of cross-referencing them may be via pytest marks (I'm not deeply familiar with pytest) to the urns (e.g. `urn:uuid:fc2bfa75-8fd0-45e0-809d-7aa3970be8ae`) andor URLs (e.g. `https://socialweb.coop/activitypub/behaviors/64d00f29-b0f5-4407-963f-5dce7c7dae2e/` but we could also eventually have a SWICG note with w3.org URLs).

Yes, I have a private branch that does that. The issue I encountered is that, given the way my tests are structured (integration tests vs unit tests), a single test may related to several behavior requirements. Like the requirement that all non-transient objects require an `id`. That applies to many tests and can't be effectively tested in isolation.

I was going to experiment with putting the URL or URN in assert statement descriptions. I can extract the related behavior "tag" from the assertion failure statement for the report. Or maybe some combination of both techniques. Still experimenting.

**Comment by gobengo** [comment]
> a single test may related to several behavior requirements

I think this is indeed a good practice as I've been thinking about how to structure tests. The more tests of any given requirement, the better. e.g. because some testing logic may only be applicable in certain contexts, so it may take a composition of several tests to have the composition apply to a wide diversity of contexts. I'm working on a writeup of this with appropriate references but a little half baked rn until then.

**Comment by gobengo** [comment]
@steve-bate The assertion path sounds promising.

Is it to simple a proposal to just use the pytest mark/annotation thing but give it a `set()` of behavior identifiers instead of a single one?

**Comment by steve-bate** [comment]
> @steve-bate The assertion path sounds promising.
> 
> Is it to simple a proposal to just use the pytest mark/annotation thing but give it a `set()` of behavior identifiers instead of a single one? Could be an easy thing while further experimenting on assertion-level-annotation.

That's definitely an option. I'll revisit my branch with the behavior pytest marks. I can at least check in the mark configuration to support experimenting with the reporting.

One of my goals is for test failure feedback to be as specific as possible. If a test covers several requirements and one of the test steps fails, it would be more challenging to diagnose the issue if the developer doesn't know *which* requirements failed.
